export type ProductLine = {
  slug: string;
  title: string;
  tagline: string;
  longIntro?: string;
  longBody?: string[];
  africaImpact?: string;
  worldImpact?: string;
  direction?: string;
  types: { name: string; note: string }[];
  promises: string[];
  outlook: { period: string; focus: string; spend: string }[];
  img: string;
  gallery?: string[];
};

export const FREE_API_KEYS = [
  { key: "jagx-59ec64942f727ec43109c48f446068fd", label: "Builder key A", note: "Free starter key for prototypes and student projects. Fair use." },
  { key: "jagx-adb6112fe4192539858e02fae18053d1", label: "Builder key B", note: "Free starter key for side projects and hackathons. Fair use." },
];

const G: Record<string, string[]> = {
  ai: ["/visual-robot.svg", "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=900&q=80", "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=900&q=80", "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=900&q=80"],
  connect: ["/brand-mark.svg", "/visual-africa.svg", "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900&q=80", "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=900&q=80"],
  os: ["/visual-os.svg", "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=900&q=80", "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900&q=80", "/visual-africa.svg"],
  silicon: ["/visual-chip.svg", "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900&q=80", "https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=900&q=80", "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=900&q=80"],
  mobility: ["/cars/horizon-front.svg", "/cars/horizon-rear.svg", "/cars/horizon-interior.svg", "/cars/courier-side.svg", "/cars/courier-rear.svg", "/cars/courier-interior.svg"],
  devices: ["/visual-os.svg", "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900&q=80", "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=900&q=80", "/visual-africa.svg"],
  cloud: ["/visual-cloud.svg", "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=900&q=80", "/visual-africa.svg"],
  education: ["/visual-edu.svg", "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=900&q=80", "/visual-africa.svg"],
  energy: ["/visual-energy.svg", "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=900&q=80", "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=900&q=80"],
  shield: ["/visual-secure.svg", "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=900&q=80", "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=900&q=80"],
  pay: ["/visual-finance.svg", "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=80", "/visual-africa.svg"],
};

export const PRODUCTS: ProductLine[] = [
  { slug: "ai", title: "JagX AI", tagline: "Multi-agent intelligence for builders, schools, and institutions.", types: [{ name: "JagX AI CLI", note: "GROUP multi-agent coding." }, { name: "JagX AI Studio", note: "Web workspace." }, { name: "JagX AI API", note: "Free starter keys." }, { name: "JagX AI Edge", note: "On-device models." }, { name: "JagX AI Gov", note: "Public sector." }], promises: ["Attributed to JagX and JRILICENSE.", "Destructive actions gated.", "Path to on-device inference.", "Free starter API keys."], outlook: [{ period: "2032–2034", focus: "Studio + API", spend: "₦60–120 billion cumulative" }, { period: "2035–2037", focus: "Edge + enterprise", spend: "₦180–300 billion cumulative" }, { period: "2038–2040+", focus: "Sovereign deployments", spend: "₦375–600 billion+ cumulative" }], img: "/visual-robot.svg", gallery: G.ai },
  { slug: "connect", title: "JagX Connect", tagline: "Secure social for Africa first.", types: [{ name: "Connect Personal", note: "Messaging and privacy." }, { name: "Buddy Circles", note: "Communities." }, { name: "Connect Business", note: "SME pages." }, { name: "Connect Secure", note: "High-risk users." }, { name: "Connect Live", note: "Events." }], promises: ["Privacy-first defaults.", "Native apps for African networks.", "Local-language moderation.", "Identity with OS and Shield."], outlook: [{ period: "2032–2034", focus: "Trust features", spend: "₦90–150 billion cumulative" }, { period: "2035–2037", focus: "Business + Secure", spend: "₦225–375 billion cumulative" }, { period: "2038–2040+", focus: "Global secure alternative", spend: "₦450–750 billion+ cumulative" }], img: "/brand-mark.svg", gallery: G.connect },
  { slug: "os", title: "JagX OS", tagline: "Privacy-first OS with on-device AI.", types: [{ name: "JagX OS Phone", note: "Consumer phones." }, { name: "JagX OS Edge", note: "Edge boards." }, { name: "JagX OS Go", note: "Entry builds." }, { name: "JagX OS Pro", note: "Enterprise." }], promises: ["JagX branding on boot.", "On-device AI with Silicon.", "Multi-year updates.", "Connect and AI first-class."], outlook: [{ period: "2032–2034", focus: "Reference devices", spend: "₦120–225 billion cumulative" }, { period: "2035–2037", focus: "Volume OS", spend: "₦300–525 billion cumulative" }, { period: "2038–2040+", focus: "Regional default OS", spend: "₦600 billion–1.05 trillion+ cumulative" }], img: "/visual-os.svg", gallery: G.os },
  { slug: "silicon", title: "JagX Silicon", tagline: "AI-first chips marked JagX.", types: [{ name: "JX-NPU", note: "Neural processing." }, { name: "JX-SEC", note: "Secure enclave." }, { name: "JX-EDGE", note: "Vision fusion." }, { name: "JX-AUTO", note: "Vehicle compute." }, { name: "JX-LAB", note: "Research silicon." }], promises: ["Packages marked JagX.", "Power for intermittent networks.", "African talent pipeline.", "Aligned with OS and AI."], outlook: [{ period: "2032–2034", focus: "Prototypes", spend: "₦150–300 billion cumulative" }, { period: "2035–2037", focus: "Volume edge chips", spend: "₦450–750 billion cumulative" }, { period: "2038–2040+", focus: "Design centers", spend: "₦900 billion–1.8 trillion+ cumulative" }], img: "/visual-chip.svg", gallery: G.silicon },
  { slug: "mobility", title: "JagX Mobility", tagline: "Full vehicles — JagX Horizon & Courier. Not a parts company. Service through 2045.", types: [{ name: "JagX Horizon", note: "Flagship city EV from ₦48,000,000." }, { name: "JagX Courier", note: "Urban utility EV from ₦32,000,000." }, { name: "Mobility Software", note: "Signed OTA, cabin AI." }, { name: "Service Network", note: "Every part returns to JagX & JRILICENSE." }], promises: ["Full vehicle — not badge-only or parts-only.", "JagX logo on grille, rear, and cabin.", "If a screw leaves the car, service is through JagX & JRILICENSE.", "Roadmap through 2045."], outlook: [{ period: "2032–2036", focus: "Horizon & Courier design; pilots", spend: "₦180–330 billion cumulative" }, { period: "2037–2041", focus: "Production + service network", spend: "₦525–900 billion cumulative" }, { period: "2042–2045+", focus: "Scaled platforms + more body styles", spend: "₦1.2–2.25 trillion+ cumulative" }], img: "/cars/horizon-front.svg", gallery: G.mobility },
  { slug: "devices", title: "JagX Devices", tagline: "Phones and edge boxes with JagX OS.", types: [{ name: "JagX Phone", note: "Flagship." }, { name: "JagX Phone Lite", note: "Affordable." }, { name: "JagX Edge Box", note: "On-prem AI." }, { name: "JagX Tablet", note: "Education." }], promises: ["JagX OS on the glass.", "Multi-year updates.", "African pricing tiers.", "Bundles with Connect and AI."], outlook: [{ period: "2032–2034", focus: "Lite + pilot", spend: "₦135–240 billion cumulative" }, { period: "2035–2037", focus: "Volume phones", spend: "₦375–600 billion cumulative" }, { period: "2038–2040+", focus: "Full family", spend: "₦750 billion–1.35 trillion+ cumulative" }], img: "/visual-os.svg", gallery: G.devices },
  { slug: "cloud", title: "JagX Cloud", tagline: "Regional cloud, Africa-first latency.", types: [{ name: "Cloud Compute", note: "VMs near users." }, { name: "Cloud AI", note: "Hosted JagX AI." }, { name: "Cloud Connect", note: "Social backends." }, { name: "Cloud Edge Link", note: "Device sync." }], promises: ["Data residency options.", "Aware of expensive bandwidth.", "Coupled with AI, Connect, OS."], outlook: [{ period: "2032–2034", focus: "First regions", spend: "₦105–195 billion cumulative" }, { period: "2035–2037", focus: "Multi-country", spend: "₦300–525 billion cumulative" }, { period: "2038–2040+", focus: "Continent-scale", spend: "₦675 billion–1.2 trillion+ cumulative" }], img: "/visual-cloud.svg", gallery: G.cloud },
  { slug: "education", title: "JagX Education", tagline: "AI literacy, labs, scholarships.", types: [{ name: "JagX Learn", note: "Courses." }, { name: "JagX Labs", note: "Community labs." }, { name: "JagX Cert", note: "Certifications." }, { name: "JagX Scholar", note: "Scholarships." }], promises: ["African language coverage.", "Low-cost tiers.", "Path to jobs."], outlook: [{ period: "2032–2034", focus: "Curriculum pilots", spend: "₦37–75 billion cumulative" }, { period: "2035–2037", focus: "Labs network", spend: "₦105–180 billion cumulative" }, { period: "2038–2040+", focus: "Builder pipeline", spend: "₦225–450 billion+ cumulative" }], img: "/visual-edu.svg", gallery: G.education },
  { slug: "energy", title: "JagX Energy", tagline: "Solar kits and microgrids.", types: [{ name: "Energy Solar Kit", note: "Solar + storage." }, { name: "Energy Device Rail", note: "Device power." }, { name: "Energy Microgrid", note: "Community packages." }], promises: ["Unreliable grid as primary case.", "Pairs with Edge Box.", "Transparent metrics."], outlook: [{ period: "2032–2034", focus: "Kits + rails", spend: "₦60–120 billion cumulative" }, { period: "2035–2037", focus: "Microgrid pilots", spend: "₦150–270 billion cumulative" }, { period: "2038–2040+", focus: "Scaled packages", spend: "₦300–600 billion+ cumulative" }], img: "/visual-energy.svg", gallery: G.energy },
  { slug: "shield", title: "JagX Shield", tagline: "Identity, ops, threat intel, audit.", types: [{ name: "Shield Identity", note: "Keys and attestation." }, { name: "Shield Ops", note: "Monitoring." }, { name: "Shield Intel", note: "Threat intel." }, { name: "Shield Audit", note: "Institution packages." }], promises: ["Security as a product.", "High-risk users.", "Aligned with Connect Secure."], outlook: [{ period: "2032–2034", focus: "Identity + Ops", spend: "₦52–105 billion cumulative" }, { period: "2035–2037", focus: "Intel + enterprise", spend: "₦135–240 billion cumulative" }, { period: "2038–2040+", focus: "Regional standard", spend: "₦270–525 billion+ cumulative" }], img: "/visual-secure.svg", gallery: G.shield },
  { slug: "pay", title: "JagX Pay", tagline: "Wallets, merchants, corridors, APIs.", types: [{ name: "Pay Wallet", note: "Consumer wallet." }, { name: "Pay Merchant", note: "SME tools." }, { name: "Pay Cross-border", note: "Remittance." }, { name: "Pay API", note: "Embed payments." }], promises: ["African merchants and diaspora first.", "Identity via Shield and Connect.", "Clear fees."], outlook: [{ period: "2032–2034", focus: "Wallet + merchant", spend: "₦75–135 billion cumulative" }, { period: "2035–2037", focus: "Corridors", spend: "₦180–330 billion cumulative" }, { period: "2038–2040+", focus: "Scale rail", spend: "₦375–675 billion+ cumulative" }], img: "/visual-finance.svg", gallery: G.pay },
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}
